### ISSUE TITLE
Arrays are not fully supported in patches 

### ISSUE THREAD

**Issue by niklaswolf** [gamestdio/colyseus-unity3d#15]
The patch Operation "add" does not work for Arrays in the gamestate. Instead, every time a new item gets pushed into it, the Operation for the patch is "replace" and the value is the full Array itself.

I could investigate this a bit further and found the origin of the Problem:
https://github.com/gamestdio/colyseus-unity3d/blob/master/Assets/Colyseus/DeltaListener/Compare.cs#L46 
the type of `oldVal` and `newVal` in such cases is NOT Dictionary, but Array. So for Arrays the condition is always false and the else-case gets done.

In the JS-Client, this Problem does not exist because `typeof [] = 'object'`.

**Comment by niklaswolf** [comment]
I'll try to solve this tomorrow ;)

**Comment by michalhainc** [comment]
Hi, I tried to resolve and tested adding new array items to room state, tested also removing, but I am not sure how the replace would work, please have a look at my pull request and evaluate... for my case locally this fix would be probably enough... let's see  #16

**Comment by PiotrChabrosAtos** [comment]
when will this be resolved? thx

**Comment by endel** [comment]
Fixed on 0.5.0 release! https://github.com/gamestdio/colyseus-unity3d/releases/tag/0.5.0
