### ISSUE TITLE
Null reference exceptions in Room.cs when any of the event handlers is not set

### ISSUE THREAD

**Issue by michalhainc** [gamestdio/colyseus-unity3d#17]
Event handlers like OnJoin in Room class are not null checked before trying to invoke.

I will fix this and send a pull request

**Comment by endel** [comment]
Thanks for reporting @michalhainc, I'm going to fix this for `v0.5.0`, which will come along with support for the latest version of the server.

**Comment by endel** [comment]
Done on branch [0.5.0](https://github.com/gamestdio/colyseus-unity3d/tree/0.5.0). Will release it soon.
