### ISSUE TITLE
Compatiblity with server v0.4.x

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus-unity3d#2]
Roadmap for compatibility with server v0.4.x:
- [x] Implement binary delta patching (https://github.com/dchest/fossil-delta-js)
- [x] Use [FossilDelta](https://github.com/endel/FossilDelta) on colyseus-unity3d client
- [x] Compute the diff between previous and new state in the client-side
- [x] Release version `colyseus-unity3d` v0.4.0

**Comment by endel** [comment]
Started working on the delta-patching port to C# here: https://github.com/endel/FossilDelta

**Comment by thebspin** [comment]
How is the progress going so far? This project seems very promising and i would like to try out the latest server version while im currently deciding on what our team should use.

**Comment by endel** [comment]
Hi @thebspin, the [dev](https://github.com/gamestdio/colyseus-unity3d/tree/dev) branch can already communicate with the last version of the server, but the "patch list" feature is still missing.

The server v0.3.x used to send the patch list directly as [JSON patch format](https://tools.ietf.org/html/rfc6902), which was then simply applied in the client-side. This has been changed in version v0.4.x - the patched state is now sent in a [binary compressed format](https://www.fossil-scm.org/index.html/doc/trunk/www/delta_format.wiki), which is faster to compute has smaller throughput. This change made unnecessary to use JSON at all in the Unity client.

Now we'd need a way to compare two arbitrary objects and provide the list of changes to the final user. I'm still evaluating the options.

**Comment by endel** [comment]
I've been rewriting this part of the system for the JavaScript client (https://github.com/gamestdio/colyseus.js/issues/3)

My plan is to have exactly the same implementation tied to the msgpack library for Unity3d.

**Comment by endel** [comment]
Version `0.4.0` released. https://github.com/gamestdio/colyseus-unity3d/releases/tag/0.4.0
