### ISSUE TITLE
Bad Checksum

### ISSUE THREAD

**Issue by sagestudios** [gamestdio/colyseus-unity3d#25]
When 5th client joins the server, then this error coming on client side.

```
Exception: bad checksum
Fossil.Delta.Apply (System.Byte[] origin, System.Byte[] delta) (at Assets/Plugins/FossilDelta/Delta.cs:204)
Colyseus.Room.Patch (System.Byte[] delta) (at Assets/Plugins/Colyseus/Room.cs:173)
Colyseus.Room.ParseMessage (System.Byte[] recv) (at Assets/Plugins/Colyseus/Room.cs:163)
Colyseus.Room.Recv () (at Assets/Plugins/Colyseus/Room.cs:73)
Colyseus.Client.Recv () (at Assets/Plugins/Colyseus/Client.cs:88)
ColyseusClient+<Start>c__Iterator0.MoveNext () (at Assets/ColyseusClient.cs:40)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

```
After this error, 5th client not getting any messages from server.

**Comment by endel** [comment]
Thanks for reporting @sagestudios. I just confirmed exactly what you described in the example project. I'll have a look into that.

How's been your experience so far with the framework? Cheers!

**Comment by sagestudios** [comment]
Hello Endel, loved the framework :) . Exactly what we are looking for in terms of features. Porting our current games will be easy. Have to test the performance and scalability. Looking forward for horizontal scaling in upcoming versions.
