### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by shophk** [gamestdio/colyseus-unity3d#28]
Hi,

I might not be using the right terms to describe what I want to achieve but please bear with me on the following description:

This is from he example code ColyseusClient.cs
	
room.Listen ("players/:id/:axis", this.OnPlayerMove);
room.Listen ("players/:id", this.OnPlayerChange);
room.Listen ("messages/:number", this.OnMessageAdded);
        room.Listen("test_messages/:odd_numbers", this.OnMessageAdded);

Where do I check to find the key axis this set in players object?
Where do I check to find the key number for messages?

How do I add new keys?
For example, 
 constructor () {
    super();

    this.setState({
      players: {},
      messages: [],
      test_messages: []
    });
  }

In test_messages I would like a key to be name "odd_numbers" instead of numbers, how to change it? Or documentation explaining this would help.

**Comment by endel** [comment]
Hi @shophk, 

I've updated the example project. Maybe it's a bit clearer now how it works.

Let me know if you still have any questions. Feel free to re-open this issue if you need to.
