### ISSUE TITLE
This property is deprecated

### ISSUE THREAD

**Issue by shophk** [gamestdio/colyseus-unity3d#29]
I opened the project using Unity 2017.2.0f3:

Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/Batch.cs(71,29): error CS0619: `UnityEngine.Application.isWebPlayer' is obsolete: `This property is deprecated and will be removed in a future version of Unity, Webplayer support has been removed since Unity 5.4'

**Comment by endel** [comment]
Hey @shophk, thanks for reporting, this is coming from the `UnityTestTools` package though, probably upgrading should fix this. I'll try to upgrade soon. Feel free to re-open this if you feel the need to. Cheers!
