### ISSUE TITLE
Getting exception when trying to Join room

### ISSUE THREAD

**Issue by rankorn** [gamestdio/colyseus-unity3d#3]
I am trying to run an example app, that just opens the connection to the server and joins a room. I am using the Chat server example, and created a small Unity app that connects.

Creating the Client works fine and I am getting the OnOpen event.

Then I am trying to join the room and I get the following 2 exceptions:
`Error: An exception has occurred during an OnMessage event., System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
at Newtonsoft.Json.Linq.JToken.get_Item (System.Object key) [0x00000] in <filename unknown>:0 
at Colyseus.Patcher.Patch (Newtonsoft.Json.Linq.JToken& document, Newtonsoft.Json.Linq.JArray patches) [0x00000] in <filename unknown>:0 
at Colyseus.Room.ApplyPatches (Newtonsoft.Json.Linq.JArray patches) [0x00000] in <filename unknown>:0 
at Colyseus.Client.OnMessageHandler (System.Object sender, WebSocketSharp.MessageEventArgs e) [0x00000] in <filename unknown>:0 
 ...
`

And:
`Error: An exception has occurred while receiving a message., WebSocketSharp.WebSocketException: The header part of a frame cannot be read from the data source.
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass7.<ReadAsync>b__6 (System.Byte[] header) [0x00000] in <filename unknown>:0 
  at WebSocketSharp.Ext+<>c__DisplayClass6.<ReadBytesAsync>b__5 (IAsyncResult ar) [0x00000] in <filename unknown>:0 
`

My join code is pretty straight forward:
`room = this.colyseus.Join ("chat_room");`

I am using the binaries, and have not checked out from git, so maybe it's a problem that was fixed?

**Comment by endel** [comment]
Hi @rankorn,

Are you using Colyseus server v0.3.x? The current Unity3D client is not yet compatible with server version 0.4.x.

Cheers!

**Comment by rankorn** [comment]
I have installed the chat server example using npm, so I am not sure which version it uses.

Is there any Unity client version that can work with 0.4? beta maybe?

I want to check out Colyseus but my client is Unity..

**Comment by endel** [comment]
@rankorn I see. Unfortunately, there's no Unity client that understands the new message format coming from server v0.4.x.

I suggest you to downgrade your server to v0.3.x - this version of the chat server is using it: https://github.com/endel/colyseus-react-example/tree/d1da67c09676049973874f3e141fc6777562f09f

The API didn't change much between those versions. I plan to implement compatibility with server v0.4.x on this library this month (https://github.com/gamestdio/colyseus-unity3d/issues/2). When it's ready you could upgrade without changing your code at all.

Cheers!

**Comment by rankorn** [comment]
Ok, will try that.
Thanks

**Comment by rankorn** [comment]
Actually getting the same problem with the old server...

**Comment by endel** [comment]
@rankorn that's odd. Thanks for your report! I will dive deep into that tonight, and hopefully have a solution by the end of the day.

**Comment by endel** [comment]
This has been fixed in the latest version, compatible with server `0.4.0`.
