### ISSUE TITLE
cannot .Listen to mutations on a string

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus-unity3d#30]
(Reported by @aloani20 on gitter)

hi guys . I have this situation . on my client I was listening to property called "turn" using `room.Listen ("turn", this.OnTurnChange);` and the state on the server look like this

```
this.setState({
dice : 0 ,
turn : "none"
});
```

but when i mutate the value of dice i could see the change on the client but changing turn did not trigger this.OnTurnChange.

I have come up with a result that mutating javascript string variable on the server did not effect the room client listener.

**Comment by endel** [comment]
The problem is exactly on this check: https://github.com/gamestdio/colyseus-unity3d/blob/f08f47d5758e0228f3e0e91b6a1b50dd1fe7aa7f/Assets/Plugins/Colyseus/DeltaListener/Compare.cs#L61-L65

It returns `true` for string changes, whereas it should return false and perform a `"replace"` operation: https://github.com/gamestdio/colyseus-unity3d/blob/f08f47d5758e0228f3e0e91b6a1b50dd1fe7aa7f/Assets/Plugins/Colyseus/DeltaListener/Compare.cs#L87-L99

**Comment by endel** [comment]
Just added a failing test scenario confirming the issue: https://github.com/gamestdio/colyseus-unity3d/commit/f08f47d5758e0228f3e0e91b6a1b50dd1fe7aa7f

**Comment by aloani20** [comment]
thanks endel.

**Comment by aloani20** [comment]
dear endel 
I checked it. It gave the same result as before. could you check it again please.

**Comment by endel** [comment]
Hey @aloani20, are you sure you checked the right version? Here's how the updated `Compare.cs` looks like: https://github.com/gamestdio/colyseus-unity3d/blob/0.5.6/Assets/Plugins/Colyseus/DeltaListener/Compare.cs#L64-L68

**Comment by aloani20** [comment]
thanks Endel woks lick a charm.

**Comment by aloani20** [comment]
lick = like. so happy it worked
