### ISSUE TITLE
data which u reciev over onData is private

### ISSUE THREAD

**Issue by Wenish** [gamestdio/colyseus-unity3d#34]
If u add a listner to onData u dont get the data

```
room.OnData += (object sender, MessageEventArgs e) => Debug.Log(e.data);
```

The data is private and so u cant accessible
![ondataisprivate](https://user-images.githubusercontent.com/18367963/37478033-7f3d1ea8-2879-11e8-9bc8-13062e06360f.png)

**Comment by endel** [comment]
Hey @Wenish,

I believe you need to cast the `data` to the type you're sending from the server-side. e.g.:

```csharp
room.OnData += (object sender, MessageEventArgs e) => {
  IndexedDictionary<string, object> data = (IndexedDictionary<string, object>) e.data;
}
```
