### ISSUE TITLE
Client which creates the room gets NullReferenceException on Startup

### ISSUE THREAD

**Issue by Wenish** [gamestdio/colyseus-unity3d#35]
On the client which creates a new room will have this NullReference:

```
NullReferenceException: Object reference not set to an instance of an object
Colyseus.Compare.Generate (GameDevWare.Serialization.IndexedDictionary`2 mirror, GameDevWare.Serialization.IndexedDictionary`2 obj, System.Collections.Generic.List`1 patches, System.Collections.Generic.List`1 path) (at Assets/Plugins/Colyseus/DeltaListener/Compare.cs:66)
Colyseus.Compare.GetPatchList (GameDevWare.Serialization.IndexedDictionary`2 tree1, GameDevWare.Serialization.IndexedDictionary`2 tree2) (at Assets/Plugins/Colyseus/DeltaListener/Compare.cs:26)
Colyseus.DeltaContainer.Set (GameDevWare.Serialization.IndexedDictionary`2 newData) (at Assets/Plugins/Colyseus/DeltaListener/DeltaContainer.cs:50)
Colyseus.Room.Patch (System.Byte[] delta) (at Assets/Plugins/Colyseus/Room.cs:177)
Colyseus.Room.ParseMessage (System.Byte[] recv) (at Assets/Plugins/Colyseus/Room.cs:163)
Colyseus.Room.Recv () (at Assets/Plugins/Colyseus/Room.cs:73)
Colyseus.Client.Recv () (at Assets/Plugins/Colyseus/Client.cs:90)
ColyseusClient+<Start>c__Iterator0.MoveNext () (at Assets/Scripts/Network/ColyseusClient.cs:55)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```
I can open other clients, join the room and everything works fine for them.

any idea why this could happen?

its pretty much the Start function from the docs:
https://github.com/BroProducts/mem-client/blob/master/MemMapPrototype/Assets/Scripts/Network/ColyseusClient.cs#L55

The Example Project modified so it has the use case which triggers the error in it
i only added 2 lines in the "server/chat_room.js" file.
Line 11 and Line 19
[colyseus-unity3d-master-null-reference.zip](https://github.com/gamestdio/colyseus-unity3d/files/1851691/colyseus-unity3d-master-null-reference.zip)

**Comment by endel** [comment]
Hi @Wenish, thanks for reporting. This looks like a bug in the [`Generate`](https://github.com/gamestdio/colyseus-unity3d/blob/master/Assets/Plugins/Colyseus/DeltaListener/Compare.cs#L66) method, which compares the new with the previous state.

Do you mind sharing the state's data structure you have in the server-side? Can I reproduce the issue by cloning your repos?

**Comment by Wenish** [comment]
hi @endel 
yes u can.

on client side its map4 in assets/scenes
maybe u have to change the ip on the network entity in the scene to localhost...
and it takes some time to open the project...

its the battleroom which i use
server code:
https://github.com/BroProducts/mem-server

**Comment by Wenish** [comment]
it seems like i only get the error when no debugger is attached to the unity editor

**Comment by Wenish** [comment]
@endel thats the old project in the repo.
im using this MemMapPrototype
im updated it there but got still the error

https://github.com/BroProducts/mem-client/blob/master/MemMapPrototype/Assets/Plugins/Colyseus/DeltaListener/Compare.cs#L56-L62

**Comment by endel** [comment]
@Wenish how can I reproduce the error? 

- I've opened Map4 on the "MemMapPrototype" project
- Started the first client on the editor
- Started the second client on a Mac build
- Right click on the screen to move both clients

Everything seems fine so far. When the error happens exactly?

**Comment by endel** [comment]
Can you explain exactly the steps you taken? Does this error happen when you're trying to run just one client from the editor preview?

**Comment by Wenish** [comment]
@endel it happens in the built version too

**Comment by endel** [comment]
@Wenish Unfortunately, I cannot reproduce here. I'd appreciate if you could send me a pull request for this.

**Comment by Wenish** [comment]
@endel i will try to reproduce the problem in a small project in the next days so its easier to fix
