### ISSUE TITLE
Support WebGL export

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus-unity3d#5]
The changes introduced in #2 are a good starting point to support Unity WebGL export.

The main issue now is to have msgpack serialization working in the browser (https://github.com/msgpack/msgpack-cli/issues/196)

**Comment by endel** [comment]
@quanglam68 suggested in the Gitter channel to use this tool instead https://www.assetstore.unity3d.com/en/#!/content/59918

**Comment by endel** [comment]
By changing the MsgPack implementation to we would need to adapt/rewrite the [DeltaListener](https://github.com/gamestdio/colyseus-unity3d/blob/master/Assets/Colyseus/DeltaListener/Compare.cs) class.

**Comment by derwish-pro** [comment]
Solution is here: https://github.com/gamestdio/colyseus-unity3d/pull/13

**Comment by endel** [comment]
Thanks @derwish-pro! Version 0.5.0 now has your implementation https://github.com/gamestdio/colyseus-unity3d/releases/tag/0.5.0
