### ISSUE TITLE
OnPlayerMove example?

### ISSUE THREAD

**Issue by hex** [gamestdio/colyseus-unity3d#6]
Hi there! I have just discovered Colyseus and I'm trying to use it in a simple Unity game just to see how it feels. I am having trouble understanding how to trigger `OnPlayerMove`. I tried something like this in Unity:
```csharp
string[] coordsX = {"x", transform.position.x.ToString() };
chatRoom.Send(coordsX);
```

but it doesn't seem to do anything. Can you give me a small example on how to do this? Thank you!

**Comment by endel** [comment]
Hi @hex!

The `OnPlayerMove` callback in the example will be triggered when the server state changes. 

The basics to use Colyseus is:

- send user input from the client to the server (usually "left pressed" is better than "x=-10")
- server computes the input and updates the state, which will later be broadcasted to all clients
- clients can then update the view

You can find the server logic for the example here: https://github.com/gamestdio/colyseus-unity3d/blob/master/Server/chat_room.js

Please let me know if you have any questions! :)
