### ISSUE TITLE
Exception: copy extends past end of input

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus-unity3d#7]
Reported by @quanglam68 in the Gitter channel:

---

hi, I still learning the unity client. testing the code given for exchanging information with 2 clients and the server works fine. ex: trace in one client : OnUpdateHandler: `{ "players" : { "SkkPLJeag" : { "x" : 520, "y" : 0 }, "HJrDLkxpx" : { "x" : 255, "y" : 0 } } }`
but when i make the data bigger in the server, `this.state.players[client.id] = { a:0, b: 0, d:0, x: 0, y: 0 };` I have an error in the client when it tries to apply the patch

```
Exception: copy extends past end of input
Fossil.Delta.Apply (System.Byte[] origin, System.Byte[] delta) (at Assets/Colyseus/FossilDelta/Delta.cs:187)
Colyseus.Room.ApplyPatch (System.Byte[] delta) (at Assets/Colyseus/Room.cs:129)
Colyseus.Client.ParseMessage (System.Byte[] recv) (at Assets/Colyseus/Client.cs:179)
Colyseus.Client.Recv () (at Assets/Colyseus/Client.cs:90)
ColyseusClient.FixedUpdate () (at Assets/Source/colyseus/ColyseusClient.cs:39)
```

My analysis is the pb appear at the call : `this._previousState = Fossil.Delta.Apply (this._previousState, delta, out error);`
seems that `_previousState` array size is too small. How can we set its size to it is bigger to match with the data set in the server

I Lost a day to understand and to change various things but I cannot find a solution / or even an quickfix

Any help is appreciated . Tks

**Comment by endel** [comment]
I'll investigate this week!

**Comment by lonewolfaka9** [comment]
facing same issue :(

**Comment by endel** [comment]
Sorry @lonewolfaka9 @quanglam68,

I believe the bad code example (server-side) was causing this problem. It was removing all user data after 5 seconds: https://github.com/gamestdio/colyseus-unity3d/commit/f349f3b55b41028f414aeed197262afc04a1976d#diff-b144d0c249b359c454ed45edd9ef619d

Please let me know if this occurs to you even after removing those lines.

**Comment by niklaswolf** [comment]
@endel same issue here :(
I am using the colyseus-starter template for the server and modified it, so unfortunatly I don't think this was the problem :/
The error occurs when the first patch is beeing processed. The first full state Exchange is working fine, an I get the following on the Client side:
```
{ "players" : [], "messages" : [] }
```
Now I'm adding a new Player in the onJoin-method of the Server and get the following on the Server:
```
StateHandler {
  players: [ SJCHVwPCl: Player { xPosition: 0, yPosition: 0, zPosition: 0 } ],
  messages: [ 'SJCHVwPCl joined!' ] `
}
```
Looking good so far!
But when it's trying to apply the patch client-side, the described error occurs...

**Comment by niklaswolf** [comment]
I investigated a bit further:
The above does NOT work in the JS-Client, too. It gives an empty Players-property.
What I then tried was too get rid of the Player-reference in the state and added a simple String ('adv') instead, so I got the following on the Server
```
StateHandler {
  players: [ Skws5wP0g: 'adv', S1V0cvv0l: 'adv' ],
  messages:
   [ 'Skws5wP0g joined!',
     'S1V0cvv0l joined!' ]
 }
```
This didn't work either on the JS-Client. It gave the same empty Players-property.

Then I tried to get rid of the object/Array completely, because the Messages-property was working fine.
So server-side it looked like this:
```
StateHandler {
  players: [ 'B1grovPAx', 'rkmUjwwCx'],
  messages:
   [ 'B1grovPAx joined!',
     'rkmUjwwCx joined!',
     ] }
```
This worked indeed on the JS-Client. But the Unity/C#-Client gives the same error as described.
Maybe this helps while investigating ;)

**Comment by endel** [comment]
@niklaswolf Do you have the project using the JavaScript client so I can have a look at? If you can also share your Unity/C# client would be great. I'd like to investigate further. Thanks

**Comment by niklaswolf** [comment]
Server: https://mygit.th-deg.de/nw17904/colyseus-server
JS-Client: https://mygit.th-deg.de/jl01849/WebVR (actually maintained by a colleague of mine)
These two are hosted on our Universitys gitlab, but we made them public, so you should be able to clone them ;)

Unity: https://github.com/niklaswolf/colyseus-unity3d (this is adapted for UWP, but it works in Unity-Editor, too. The error is also showing up in Unity ;))

**Comment by endel** [comment]
@niklaswolf unfortunately, I don't have rights to clone these repositories. Do you mind sending them to me at endel.dreyer [at] gmail.com? Thanks!

**Comment by niklaswolf** [comment]
@endel
I just sent you an email ;)

**Comment by niklaswolf** [comment]
Any news on this? :)

**Comment by endel** [comment]
Hi @niklaswolf, thanks for sending the sources. I hope to find some time during this week to check it out. Sorry.

**Comment by endel** [comment]
Yup, the error is still happening. 😢 

Here's a report of what I could find:
- The error never occurs for the first client.
- The problem happens when the second client receives the first patch message from the server.
- I believe the root cause of the issue on `Room#SetState()`: https://github.com/gamestdio/colyseus-unity3d/blob/master/Assets/Colyseus/Room.cs#L93
- The client should have the latest encoded state (as `byte[]` of the msgpack object), to be able to apply patches against it later.

I've asked how to re-encode a `MessagePackObject` into `byte[]` here, as I couldn't find out how to do it: https://github.com/msgpack/msgpack-cli/issues/234

Any help is very appreciated. :)

**Comment by niklaswolf** [comment]
@endel I tried the suggestion the guy from msgpack made, and it seems to work! If you don't mind, I'll make a PR to include this solution! :)

**Comment by endel** [comment]
@niklaswolf awesome. Sure, that'd be great! Thanks! :)

**Comment by endel** [comment]
It's finally fixed! Thanks @niklaswolf for your pull-request! 🎉
