### ISSUE TITLE
Windows UWP-Support

### ISSUE THREAD

**Issue by niklaswolf** [gamestdio/colyseus-unity3d#8]
Hi, I want to use colyseus in a project where I have to write a Unity Windows UWP App. When I wanted to build the project, I got an error message because the WebSocket implementation doesn't work on UWP. 
Now I thought I could add another preprocessor-directive in WebSocket.cs and write the needed functions with a WebSocket implementation for UWP (https://docs.microsoft.com/en-us/windows/uwp/networking/websockets).

I just wanted to make sure, which functions I have to write for this. I'm thinking, it's 
```
Send()
Recv()
Connect()
Close()
```

am I right?

**Comment by endel** [comment]
Hi @niklaswolf,

That's right, that's the only methods used from the [WebSocket client](https://github.com/sta/websocket-sharp) right now. I thought websocket-sharp had support for all platforms. 

I'm not a Windows user, so I'm usually building this project using Mono. Please let me know if you need any help. Cheers!

**Comment by niklaswolf** [comment]
Hi,
yeah it seems like websocket-sharp is supporting nearly every platform besides UWP. :(
After digging a bit deeper, I found that websocket-sharp is used in two other files, Client.cs and Room.cs. For these files I have another question: where is `EventHandler.Emit()` coming from (for example https://github.com/gamestdio/colyseus-unity3d/blob/master/Assets/Colyseus/Room.cs#L79)? Is it defined by websocket-sharp, too?

Another thing that could be problematic is MessagePack: I did not have a further look into it, but I get some errors here, too, so my question is which version are you using?

**Comment by endel** [comment]
@niklaswolf that's just a regular [C# EventHandler](https://msdn.microsoft.com/en-us/library/db0etb8x(v=vs.110).aspx). It's a public API to listen to events when you have your Room instantiated.

For MsgPack I'm using a Unity3D-compatible build, from version [0.9.0-beta1](https://github.com/msgpack/msgpack-cli/releases/tag/0.9.0-beta1). For UWP you can try using a different dll, or maybe building the sources yourself.

**Comment by niklaswolf** [comment]
@endel okay this `Emit()`-function still is a bit mysterious for me, as I can't find it in any documentation. But I'll try to get this working for UWP next week.
By the way thanks for your great support! :)

**Comment by endel** [comment]
Thanks for this! Closing as it was implemented by yourself here :) https://github.com/gamestdio/colyseus-unity3d/pull/10
